### ISSUE TITLE
What is the status of fuse3?

### ISSUE THREAD

**Issue by theWebalyst** [Sherlock-Holo/fuse3#1]
I'm looking at Rust fuse libs for a distributed FS and wonder what is the status of fuse3?

`cargo build` in `./examples` succeeds (with a handful of warnings) but am not sure how to run them?

`cargo build` in `./` fails with an error:
```
error[E0277]: the trait bound `(): std::future::Future` is not satisfied
  --> src/spawn.rs:16:38
   |
16 | pub fn spawn_blocking<F, T>(f: F) -> impl Future<Output = T>
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::future::Future` is not implemented for `()`
   |
   = note: the return type of a function must have a statically known size

error: aborting due to previous error; 35 warnings emitted

For more information about this error, try `rustc --explain E0277`.
error: could not compile `fuse3`.
```

I'm still new to Rust so maybe missing something obvious. Thanks.

**Comment by Sherlock-Holo** [comment]
this is a rust lib with some features, if you want to use it, you must enable the feature `tokio-runtime` or `async-std-runtime`.

in `examples` it enable feature `async-std-runtime` by default so `cargo build` will succeed

**Comment by theWebalyst** [comment]
Thanks. How do I run the examples?

**Comment by Sherlock-Holo** [comment]
sorry for the late reply @happybeing .
cd into the example directory and run `cargo run`

**Comment by jason-ni** [comment]
Hi @Sherlock-Holo 

I tried to compile examples today and found an issue about `RawFd`:
```
the trait `std::os::unix::io::AsRawFd` is not implemented for `i32`
```

It's because I was using rust stable 1.47 version which lacks the fix of RawFd implementation: https://github.com/rust-lang/rust/pull/76969. And after upgrade to 1.50, it can be compiled. 

So I suggest you add a requirement of the rust toolchain version to avoid this pitfall. 

And thank you for this great project I have been looking forward for a long time!

**Comment by Sherlock-Holo** [comment]
@jason-ni i always use the nightly version toolchains so never found this problem, thanks for your advice

**Comment by Sherlock-Holo** [comment]
the minimum rust version is added into the README @jason-ni

**Comment by jason-ni** [comment]
Thank you!
Sorry for the late response. I saw that change days ago but missed the notification however.

**Comment by Sherlock-Holo** [comment]
> Thank you!
> Sorry for the late response. I saw that change days ago but missed the notification however.

I push some beta version for the new version, you can have a try for this and give me some advise if you found some api can be better
